# Generated by Django 3.2.3 on 2021-05-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_categ',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(default='', upload_to='ShopSite/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_subcateg',
            field=models.CharField(default='', max_length=50),
        ),
    ]
