# Generated by Django 3.2.3 on 2021-05-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopSite', '0002_auto_20210526_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('dbmsg_id', models.AutoField(primary_key=True, serialize=False)),
                ('dbname', models.CharField(default='', max_length=50)),
                ('dbemail', models.CharField(default='', max_length=50)),
                ('dbphone', models.CharField(default='', max_length=40)),
                ('dbmessage', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
